---
apiVersion: v1
kind: Namespace
metadata:
  name: ssh-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-server
  namespace: ssh-server
  labels:
    app: ssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-server
  template:
    metadata:
      labels:
        app: ssh-server
    spec:
      containers:
      - image: docker.io/thanosz/alpine-sshd   
        imagePullPolicy: Always
        name: ssh-server
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: params
          mountPath: /params/
        - name: home
          mountPath: /home
      volumes:
      - name: params
        persistentVolumeClaim:
          claimName: claim-ssh-params
      - name: home
        persistentVolumeClaim:
          claimName: claim-ssh-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-ssh-params
  namespace: ssh-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-ssh-home
  namespace: ssh-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
  namespace: ssh-server
spec:
  type: LoadBalancer
  selector:
    app: ssh-server
  ports:
    - port: 2222
      protocol: TCP
      targetPort: 2222
      name: port-2222

    - port: 9090
      protocol: TCP
      name: port-9090

    - port: 9091
      protocol: TCP
      name: port-9091

    - port: 9092
      protocol: TCP
      name: port-9092

    - port: 9093
      protocol: TCP
      name: port-9093

    - port: 9094
      protocol: TCP
      name: port-9094

    - port: 9095
      protocol: TCP
      name: port-30905

    - port: 9096
      protocol: TCP
      name: port-30906

    - port: 9097
      protocol: TCP
      name: port-30907

    - port: 9098
      protocol: TCP
      name: port-9095

    - port: 9099
      protocol: TCP
      name: port-9099

    - port: 9100
      protocol: TCP
      name: port-9100

    - port: 9101
      protocol: TCP
      name: port-9101

    - port: 9102
      protocol: TCP
      name: port-9102

    - port: 9103
      protocol: TCP
      name: port-9103

    - port: 9104
      protocol: TCP
      name: port-9104

    - port: 9105
      protocol: TCP
      name: port-9105
